DO $$ BEGIN CREATE TYPE public.user_role AS ENUM ('Operator', 'Supervisor', 'Admin', 'Super-Admin', 'HR'); EXCEPTION WHEN duplicate_object THEN null; END $$;
DO $$ BEGIN CREATE TYPE public.profile_status AS ENUM ('Active', 'On Leave', 'Inactive', 'Suspended'); EXCEPTION WHEN duplicate_object THEN null; END $$;
DO $$ BEGIN CREATE TYPE public.absence_type AS ENUM ('annual_leave', 'sick_leave', 'maternity_leave', 'paternity_leave', 'compassionate_leave', 'study_leave', 'unpaid_leave', 'public_holiday'); EXCEPTION WHEN duplicate_object THEN null; END $$;
DO $$ BEGIN CREATE TYPE public.request_status AS ENUM ('pending', 'approved', 'declined', 'cancelled'); EXCEPTION WHEN duplicate_object THEN null; END $$;
DO $$ BEGIN CREATE TYPE public.shift_status AS ENUM ('draft', 'active', 'cancelled', 'completed'); EXCEPTION WHEN duplicate_object THEN null; END $$;
DO $$ BEGIN CREATE TYPE public.assignment_status AS ENUM ('assigned', 'open', 'at_risk', 'cancelled'); EXCEPTION WHEN duplicate_object THEN null; END $$;
DO $$ BEGIN CREATE TYPE public.audit_action AS ENUM ('created', 'assigned', 'unassigned', 'modified', 'cancelled', 'swapped'); EXCEPTION WHEN duplicate_object THEN null; END $$;
DO $$ BEGIN CREATE TYPE public.skill_level AS ENUM ('required', 'preferred', 'nice_to_have'); EXCEPTION WHEN duplicate_object THEN null; END $$;
DO $$ BEGIN CREATE TYPE public.chat_room_type AS ENUM ('general', 'dm'); EXCEPTION WHEN duplicate_object THEN null; END $$;

CREATE TABLE IF NOT EXISTS public.profiles (id UUID NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY, user_id UUID NOT NULL UNIQUE REFERENCES auth.users(id) ON DELETE CASCADE, name TEXT NOT NULL, role user_role NOT NULL DEFAULT 'Operator', status profile_status NOT NULL DEFAULT 'Active', created_at TIMESTAMPTZ NOT NULL DEFAULT now(), updated_at TIMESTAMPTZ NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS public.noticeboard (id UUID NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY, content TEXT NOT NULL DEFAULT '', updated_by UUID REFERENCES auth.users(id) ON DELETE SET NULL, created_at TIMESTAMPTZ NOT NULL DEFAULT now(), updated_at TIMESTAMPTZ NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS public.news_items (id UUID NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY, user_id UUID NOT NULL, title TEXT NOT NULL, client_id TEXT NOT NULL, description TEXT, date TIMESTAMPTZ NOT NULL, valid_until TIMESTAMPTZ NOT NULL, created_at TIMESTAMPTZ NOT NULL DEFAULT now(), category TEXT NOT NULL, created_at_iso TEXT NOT NULL, updated_at TIMESTAMPTZ NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS public.system_users (id UUID NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY, user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE, name TEXT NOT NULL, role TEXT NOT NULL DEFAULT 'Operator', email TEXT NOT NULL, status TEXT NOT NULL DEFAULT 'Active', created_at TIMESTAMPTZ NOT NULL DEFAULT now(), updated_at TIMESTAMPTZ NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS public.comprehensive_users (id UUID NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY, auth_user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE, name TEXT NOT NULL, email TEXT NOT NULL, phone_number TEXT, role TEXT NOT NULL DEFAULT 'Operator', status TEXT NOT NULL DEFAULT 'Active', employee_id TEXT, department TEXT, position TEXT, contract_type TEXT DEFAULT 'full_time', working_hours_per_week NUMERIC DEFAULT 37.5, start_date DATE, annual_leave_entitlement NUMERIC DEFAULT 25.0, date_of_birth DATE, ni_number TEXT, address_line1 TEXT, address_line2 TEXT, city TEXT, postal_code TEXT, country TEXT DEFAULT 'United Kingdom', emergency_contact_name TEXT, emergency_contact_phone TEXT, emergency_contact_relationship TEXT, salary NUMERIC, bank_name TEXT, bank_account_number TEXT, bank_sort_code TEXT, is_system_user BOOLEAN DEFAULT false, is_staff_member BOOLEAN DEFAULT false, line_manager_id UUID, created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(), updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
CREATE TABLE IF NOT EXISTS public.customers (id UUID NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY, user_id UUID NOT NULL, name TEXT NOT NULL, business_type TEXT, address_line1 TEXT, address_line2 TEXT, city TEXT, postcode TEXT, tel TEXT, mobile TEXT, email TEXT, website TEXT, status TEXT NOT NULL DEFAULT 'Active', contact TEXT, phone TEXT, packages JSONB DEFAULT '[]'::jsonb, calls_per_month TEXT, billing_day DATE, billing_options TEXT DEFAULT 'VAT', billing_status JSONB DEFAULT '[]'::jsonb, additional_services JSONB DEFAULT '[]'::jsonb, call_handling_tier TEXT, contacts JSONB DEFAULT '[]'::jsonb, address TEXT, outcome_how TEXT, outcome_when TEXT, outcome_format TEXT, message_selection TEXT, filters TEXT, system_link TEXT, script TEXT, script_tags JSONB DEFAULT '[]'::jsonb, created_at TIMESTAMPTZ NOT NULL DEFAULT now(), updated_at TIMESTAMPTZ NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS public.billing_customers (customer_id UUID PRIMARY KEY DEFAULT gen_random_uuid(), name TEXT NOT NULL, telephone TEXT, package_name TEXT, base_call_allowance INTEGER DEFAULT 0, monthly_charge DECIMAL(10,2) DEFAULT 0, rate_per_call DECIMAL(10,4) DEFAULT 0, rate_per_minute DECIMAL(10,4) DEFAULT 0, rate_sms DECIMAL(10,4) DEFAULT 0, rate_transfer_landline DECIMAL(10,4) DEFAULT 0, rate_transfer_mobile DECIMAL(10,4) DEFAULT 0, active BOOLEAN DEFAULT true, created_at TIMESTAMPTZ DEFAULT now(), updated_at TIMESTAMPTZ DEFAULT now());
CREATE TABLE IF NOT EXISTS public.customer_pricing (id UUID NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY, customer_id UUID NOT NULL REFERENCES public.billing_customers(customer_id), effective_from DATE NOT NULL, per_call_rate_pence INTEGER NOT NULL, overage_per_minute_pence INTEGER NOT NULL, std_included_seconds INTEGER NOT NULL DEFAULT 180, notes TEXT, created_at TIMESTAMPTZ NOT NULL DEFAULT now(), updated_at TIMESTAMPTZ NOT NULL DEFAULT now(), UNIQUE(customer_id, effective_from));
CREATE TABLE IF NOT EXISTS public.staff_details (id UUID NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY, user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE UNIQUE, employee_id TEXT UNIQUE, department TEXT, position TEXT, line_manager_id UUID REFERENCES auth.users(id), start_date DATE, contract_type TEXT DEFAULT 'full_time', working_hours_per_week DECIMAL(4,1) DEFAULT 37.5, salary DECIMAL(10,2), emergency_contact_name TEXT, emergency_contact_phone TEXT, emergency_contact_relationship TEXT, address_line1 TEXT, address_line2 TEXT, city TEXT, postal_code TEXT, country TEXT DEFAULT 'United Kingdom', phone_number TEXT, date_of_birth DATE, ni_number TEXT, bank_name TEXT, bank_account_number TEXT, bank_sort_code TEXT, created_at TIMESTAMPTZ NOT NULL DEFAULT now(), updated_at TIMESTAMPTZ NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS public.employee_sensitive_data (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), user_id UUID NOT NULL UNIQUE, date_of_birth DATE, full_address TEXT, emergency_contact_name TEXT, emergency_contact_phone TEXT, emergency_contact_relationship TEXT, created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(), updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(), last_accessed_by UUID, last_accessed_at TIMESTAMPTZ, access_count INTEGER DEFAULT 0);
CREATE TABLE IF NOT EXISTS public.employee_financial_data (id uuid NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY, user_id uuid NOT NULL UNIQUE, salary numeric, bank_name text, bank_account_number text, bank_sort_code text, ni_number text, created_at TIMESTAMPTZ NOT NULL DEFAULT now(), updated_at TIMESTAMPTZ NOT NULL DEFAULT now(), last_accessed_by uuid, last_accessed_at TIMESTAMPTZ);
CREATE TABLE IF NOT EXISTS public.scheduler_settings (id UUID NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY, setting_key TEXT NOT NULL UNIQUE, setting_value JSONB NOT NULL, description TEXT, updated_by UUID NOT NULL, updated_at TIMESTAMPTZ NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS public.form_templates (id uuid NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY, name text NOT NULL, description text NOT NULL DEFAULT '', form_type text NOT NULL DEFAULT 'lead_capture', elements jsonb NOT NULL DEFAULT '[]'::jsonb, brand_color text NOT NULL DEFAULT '#1a2332', is_active boolean NOT NULL DEFAULT true, created_by uuid NOT NULL, created_at TIMESTAMPTZ NOT NULL DEFAULT now(), updated_at TIMESTAMPTZ NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS public.form_submissions (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), form_template_id uuid NOT NULL REFERENCES public.form_templates(id) ON DELETE CASCADE, customer_id uuid NOT NULL REFERENCES public.customers(id) ON DELETE CASCADE, data jsonb NOT NULL DEFAULT '{}'::jsonb, submitted_at TIMESTAMPTZ NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS public.proposal_tokens (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), customer_id uuid NOT NULL REFERENCES public.customers(id) ON DELETE CASCADE, token text NOT NULL UNIQUE, created_by uuid NOT NULL, expires_at TIMESTAMPTZ NOT NULL, used_at TIMESTAMPTZ, proposal_data jsonb DEFAULT '{}'::jsonb, created_at TIMESTAMPTZ NOT NULL DEFAULT now(), updated_at TIMESTAMPTZ NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS public.document_shares (id UUID NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY, document_type TEXT NOT NULL, document_id UUID NOT NULL, shared_by UUID NOT NULL REFERENCES auth.users(id), share_token TEXT NOT NULL UNIQUE, expires_at TIMESTAMPTZ, is_active BOOLEAN NOT NULL DEFAULT true, created_at TIMESTAMPTZ NOT NULL DEFAULT now(), updated_at TIMESTAMPTZ NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS public.app_permissions (id UUID NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY, section TEXT NOT NULL, feature TEXT NOT NULL, icon TEXT, description TEXT, created_at TIMESTAMPTZ NOT NULL DEFAULT now(), updated_at TIMESTAMPTZ NOT NULL DEFAULT now(), UNIQUE(section, feature));
CREATE TABLE IF NOT EXISTS public.status_timing_logs (id UUID NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY, user_id UUID NOT NULL, status TEXT NOT NULL, action TEXT NOT NULL, timestamp TIMESTAMPTZ NOT NULL DEFAULT now(), created_at TIMESTAMPTZ NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS public.user_status (id UUID NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY, user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE, status TEXT NOT NULL DEFAULT 'offline', custom_message TEXT, created_at TIMESTAMPTZ NOT NULL DEFAULT now(), updated_at TIMESTAMPTZ NOT NULL DEFAULT now(), UNIQUE(user_id));
CREATE TABLE IF NOT EXISTS public.user_statuses (id UUID NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY, user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE, status TEXT NOT NULL DEFAULT 'offline', status_emoji TEXT DEFAULT '⛔', auto_reset_at TIMESTAMPTZ, created_at TIMESTAMPTZ NOT NULL DEFAULT now(), updated_at TIMESTAMPTZ NOT NULL DEFAULT now(), UNIQUE(user_id));
CREATE TABLE IF NOT EXISTS public.todos (id UUID NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY, user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE, text TEXT NOT NULL, completed BOOLEAN NOT NULL DEFAULT false, created_at TIMESTAMPTZ NOT NULL DEFAULT now(), updated_at TIMESTAMPTZ NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS public.project_tasks (id UUID NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY, title TEXT NOT NULL, description TEXT, status TEXT NOT NULL DEFAULT 'To Do', priority TEXT NOT NULL DEFAULT 'Medium', assignee_id TEXT, due_date TIMESTAMPTZ, created_by UUID NOT NULL, customer_id UUID REFERENCES public.customers(id), time_spent NUMERIC DEFAULT 0, created_at TIMESTAMPTZ NOT NULL DEFAULT now(), updated_at TIMESTAMPTZ NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS public.task_attachments (id UUID NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY, task_id UUID NOT NULL REFERENCES public.project_tasks(id) ON DELETE CASCADE, file_name TEXT NOT NULL, file_path TEXT NOT NULL, file_size INTEGER NOT NULL DEFAULT 0, content_type TEXT NOT NULL DEFAULT 'application/octet-stream', uploaded_by UUID NOT NULL, created_at TIMESTAMPTZ NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS public.task_notifications (id UUID NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY, task_id UUID NOT NULL REFERENCES public.project_tasks(id) ON DELETE CASCADE, user_id UUID NOT NULL, type TEXT NOT NULL, message TEXT NOT NULL, is_read BOOLEAN NOT NULL DEFAULT false, created_at TIMESTAMPTZ NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS public.app_permission_grants (id UUID NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY, permission_id UUID NOT NULL REFERENCES public.app_permissions(id) ON DELETE CASCADE, role TEXT NOT NULL, granted BOOLEAN NOT NULL DEFAULT false, created_at TIMESTAMPTZ NOT NULL DEFAULT now(), updated_at TIMESTAMPTZ NOT NULL DEFAULT now(), UNIQUE(permission_id, role));
CREATE TABLE IF NOT EXISTS public.billing_settings (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), vat_rate DECIMAL(5,4) NOT NULL DEFAULT 0.20, default_package TEXT DEFAULT 'Standard', default_call_rate DECIMAL(10,4) DEFAULT 0.50, created_at TIMESTAMPTZ DEFAULT now(), updated_at TIMESTAMPTZ DEFAULT now());
CREATE TABLE IF NOT EXISTS public.import_batches (batch_id UUID PRIMARY KEY DEFAULT gen_random_uuid(), source TEXT NOT NULL, uploaded_by UUID, uploaded_at TIMESTAMPTZ DEFAULT now(), total_records INTEGER DEFAULT 0, processed_count INTEGER DEFAULT 0, error_count INTEGER DEFAULT 0, status TEXT DEFAULT 'pending', billing_period TEXT);
CREATE TABLE IF NOT EXISTS public.call_logs (call_id UUID PRIMARY KEY DEFAULT gen_random_uuid(), customer_id UUID REFERENCES public.billing_customers(customer_id), customer_name TEXT, caller_number TEXT, call_started_at TIMESTAMPTZ, call_ended_at TIMESTAMPTZ, duration_seconds INTEGER DEFAULT 0, call_type TEXT DEFAULT 'inbound', status TEXT DEFAULT 'completed', notes TEXT, billing_period TEXT, date DATE, batch_id UUID REFERENCES public.import_batches(batch_id), created_at TIMESTAMPTZ DEFAULT now());
CREATE TABLE IF NOT EXISTS public.billing_periods (id UUID NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY, customer_id UUID NOT NULL REFERENCES public.billing_customers(customer_id), period_label TEXT NOT NULL, period_start DATE NOT NULL, period_end DATE NOT NULL, total_calls INTEGER NOT NULL DEFAULT 0, included_calls INTEGER NOT NULL DEFAULT 0, overage_calls INTEGER NOT NULL DEFAULT 0, total_seconds INTEGER NOT NULL DEFAULT 0, base_charge_pence INTEGER NOT NULL DEFAULT 0, overage_charge_pence INTEGER NOT NULL DEFAULT 0, total_charge_pence INTEGER NOT NULL DEFAULT 0, vat_rate NUMERIC(5,4) NOT NULL DEFAULT 0.20, status TEXT NOT NULL DEFAULT 'draft', created_at TIMESTAMPTZ NOT NULL DEFAULT now(), updated_at TIMESTAMPTZ NOT NULL DEFAULT now(), UNIQUE(customer_id, period_label));
CREATE TABLE IF NOT EXISTS public.billing_invoices (invoice_id UUID PRIMARY KEY DEFAULT gen_random_uuid(), customer_id UUID REFERENCES public.billing_customers(customer_id), billing_period TEXT NOT NULL, base_calls_allowed INTEGER DEFAULT 0, calls_made INTEGER DEFAULT 0, extra_calls INTEGER DEFAULT 0, total_minutes DECIMAL(10,2) DEFAULT 0, extra_minutes DECIMAL(10,2) DEFAULT 0, extra_charges DECIMAL(10,2) DEFAULT 0, base_charge DECIMAL(10,2) DEFAULT 0, total_invoice DECIMAL(10,2) DEFAULT 0, vat_rate DECIMAL(5,4) DEFAULT 0.20, total_with_vat DECIMAL(10,2) DEFAULT 0, created_on TIMESTAMPTZ DEFAULT now(), updated_at TIMESTAMPTZ DEFAULT now());
CREATE TABLE IF NOT EXISTS public.billing_line_items (id UUID NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY, billing_period_id UUID NOT NULL REFERENCES public.billing_periods(id) ON DELETE CASCADE, call_id UUID NOT NULL REFERENCES public.call_logs(call_id), per_call_rate_pence INTEGER NOT NULL, overage_per_minute_pence INTEGER NOT NULL, std_included_seconds INTEGER NOT NULL, duration_seconds INTEGER NOT NULL, overage_minutes INTEGER NOT NULL DEFAULT 0, charge_per_call_pence INTEGER NOT NULL, charge_overage_pence INTEGER NOT NULL DEFAULT 0, total_charge_pence INTEGER NOT NULL, is_overage BOOLEAN NOT NULL DEFAULT false, created_at TIMESTAMPTZ NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS public.billing_data_audit (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), accessed_by uuid NOT NULL REFERENCES auth.users(id), customer_id uuid, action text NOT NULL, table_name text NOT NULL, accessed_at TIMESTAMPTZ DEFAULT now(), ip_address inet, user_agent text);
CREATE TABLE IF NOT EXISTS public.chat_rooms (id UUID NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY, name TEXT, type chat_room_type NOT NULL DEFAULT 'general', created_by UUID NOT NULL, created_at TIMESTAMPTZ NOT NULL DEFAULT now(), updated_at TIMESTAMPTZ NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS public.chat_messages (id UUID NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY, room_id UUID NOT NULL REFERENCES public.chat_rooms(id) ON DELETE CASCADE, sender_id UUID NOT NULL, content TEXT NOT NULL, created_at TIMESTAMPTZ NOT NULL DEFAULT now(), updated_at TIMESTAMPTZ NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS public.chat_room_members (id UUID NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY, room_id UUID NOT NULL REFERENCES public.chat_rooms(id) ON DELETE CASCADE, user_id UUID NOT NULL, joined_at TIMESTAMPTZ NOT NULL DEFAULT now(), UNIQUE(room_id, user_id));
CREATE TABLE IF NOT EXISTS public.chat_message_reads (id UUID NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY, message_id UUID NOT NULL REFERENCES public.chat_messages(id) ON DELETE CASCADE, user_id UUID NOT NULL, read_at TIMESTAMPTZ NOT NULL DEFAULT now(), UNIQUE(message_id, user_id));
CREATE TABLE IF NOT EXISTS public.holiday_entitlements (id UUID NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY, user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE, year INTEGER NOT NULL, annual_leave_entitlement NUMERIC NOT NULL DEFAULT 25.0, annual_leave_used NUMERIC NOT NULL DEFAULT 0, sick_leave_entitlement NUMERIC NOT NULL DEFAULT 10.0, sick_leave_used NUMERIC NOT NULL DEFAULT 0, personal_days_entitlement NUMERIC NOT NULL DEFAULT 5.0, personal_days_used NUMERIC NOT NULL DEFAULT 0, carried_over NUMERIC NOT NULL DEFAULT 0, created_at TIMESTAMPTZ NOT NULL DEFAULT now(), updated_at TIMESTAMPTZ NOT NULL DEFAULT now(), UNIQUE(user_id, year));
CREATE TABLE IF NOT EXISTS public.holiday_requests (id UUID NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY, user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE, start_date DATE NOT NULL, end_date DATE NOT NULL, absence_type absence_type NOT NULL DEFAULT 'annual_leave', status request_status NOT NULL DEFAULT 'pending', notes TEXT, approved_by UUID REFERENCES auth.users(id), created_at TIMESTAMPTZ NOT NULL DEFAULT now(), updated_at TIMESTAMPTZ NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS public.shift_templates (id UUID NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY, name TEXT NOT NULL, start_time TIME NOT NULL, end_time TIME NOT NULL, required_staff INTEGER NOT NULL DEFAULT 1, color TEXT DEFAULT '#3B82F6', status shift_status NOT NULL DEFAULT 'active', recurrence_pattern JSONB, created_by UUID NOT NULL, created_at TIMESTAMPTZ NOT NULL DEFAULT now(), updated_at TIMESTAMPTZ NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS public.shift_instances (id UUID NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY, template_id UUID NOT NULL REFERENCES public.shift_templates(id) ON DELETE CASCADE, shift_date DATE NOT NULL, start_time TIME NOT NULL, end_time TIME NOT NULL, required_staff INTEGER NOT NULL DEFAULT 1, status shift_status NOT NULL DEFAULT 'active', notes TEXT, created_at TIMESTAMPTZ NOT NULL DEFAULT now(), updated_at TIMESTAMPTZ NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS public.shift_assignments (id UUID NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY, shift_instance_id UUID NOT NULL REFERENCES public.shift_instances(id) ON DELETE CASCADE, user_id UUID NOT NULL, status assignment_status NOT NULL DEFAULT 'assigned', assigned_by UUID NOT NULL, notes TEXT, created_at TIMESTAMPTZ NOT NULL DEFAULT now(), updated_at TIMESTAMPTZ NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS public.shift_audit_log (id UUID NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY, shift_instance_id UUID REFERENCES public.shift_instances(id) ON DELETE SET NULL, action audit_action NOT NULL, performed_by UUID NOT NULL, target_user_id UUID, details JSONB, created_at TIMESTAMPTZ NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS public.user_skills (id UUID NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY, user_id UUID NOT NULL, skill_name TEXT NOT NULL, level skill_level NOT NULL DEFAULT 'preferred', created_at TIMESTAMPTZ NOT NULL DEFAULT now(), UNIQUE(user_id, skill_name));
CREATE TABLE IF NOT EXISTS public.sensitive_data_access_log (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), accessed_by uuid NOT NULL, target_user_id uuid, table_name text NOT NULL, action text NOT NULL, ip_address inet, user_agent text, accessed_at TIMESTAMPTZ NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS public.sensitive_data_audit (id UUID NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY, user_id UUID NOT NULL, accessed_table TEXT NOT NULL, accessed_field TEXT, action TEXT NOT NULL, accessed_at TIMESTAMPTZ NOT NULL DEFAULT now(), ip_address TEXT, user_agent TEXT);
CREATE TABLE IF NOT EXISTS public.staff_data_access_audit (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), accessed_by uuid NOT NULL, target_user_id uuid, data_type text NOT NULL, action text NOT NULL DEFAULT 'view', fields_accessed text[], accessed_at TIMESTAMPTZ NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS public.system_users_audit_log (id UUID NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY, performed_by UUID NOT NULL, target_user_id UUID NOT NULL, action TEXT NOT NULL, old_values JSONB, new_values JSONB, created_at TIMESTAMPTZ NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS public.financial_data_audit_enhanced (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), user_id uuid NOT NULL, target_user_id uuid, action text NOT NULL, data_category text NOT NULL DEFAULT 'financial', fields_accessed text[], ip_address inet, user_agent text, session_id text, risk_level text DEFAULT 'normal', created_at TIMESTAMPTZ NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS public.financial_emergency_access (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), user_id uuid NOT NULL, target_user_id uuid NOT NULL, reason text NOT NULL, approved_by uuid, approved_at TIMESTAMPTZ, expires_at TIMESTAMPTZ NOT NULL, is_active boolean DEFAULT true, created_at TIMESTAMPTZ NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS public.leave_quota_defaults (year integer primary key, base_annual numeric not null default 25.0, bank_holidays numeric not null default 10.0, christmas_closure_days numeric not null default 5.0, created_at TIMESTAMPTZ not null default now(), updated_at TIMESTAMPTZ not null default now(), applied_at TIMESTAMPTZ);

-- Extra columns
ALTER TABLE public.app_permission_grants ADD COLUMN IF NOT EXISTS scope TEXT NOT NULL DEFAULT 'all';
ALTER TABLE public.call_logs ADD COLUMN IF NOT EXISTS is_sms BOOLEAN DEFAULT false;
ALTER TABLE public.customers ADD COLUMN IF NOT EXISTS va_package TEXT;
ALTER TABLE public.customers ADD COLUMN IF NOT EXISTS va_price NUMERIC;
ALTER TABLE public.customers ADD COLUMN IF NOT EXISTS vr_package TEXT;
ALTER TABLE public.customers ADD COLUMN IF NOT EXISTS vr_price NUMERIC;
ALTER TABLE public.customers ADD COLUMN IF NOT EXISTS lead_metadata JSONB DEFAULT '{}'::jsonb;
ALTER TABLE public.customers ADD COLUMN IF NOT EXISTS cl_package TEXT;
ALTER TABLE public.customers ADD COLUMN IF NOT EXISTS cl_price NUMERIC;
ALTER TABLE public.customers ADD COLUMN IF NOT EXISTS cl_included_minutes INTEGER;
ALTER TABLE public.customers ADD COLUMN IF NOT EXISTS cl_overage_rate NUMERIC;
ALTER TABLE public.customers ADD COLUMN IF NOT EXISTS ai_package TEXT;
ALTER TABLE public.customers ADD COLUMN IF NOT EXISTS ai_price NUMERIC;
ALTER TABLE public.customers ADD COLUMN IF NOT EXISTS dt_package TEXT;
ALTER TABLE public.customers ADD COLUMN IF NOT EXISTS dt_price NUMERIC;
ALTER TABLE public.document_shares ADD COLUMN IF NOT EXISTS password_hash TEXT;
ALTER TABLE public.employee_financial_data ADD COLUMN IF NOT EXISTS encrypted_salary TEXT;
ALTER TABLE public.employee_financial_data ADD COLUMN IF NOT EXISTS encrypted_bank_account TEXT;
ALTER TABLE public.employee_financial_data ADD COLUMN IF NOT EXISTS encrypted_bank_sort_code TEXT;
ALTER TABLE public.employee_financial_data ADD COLUMN IF NOT EXISTS encrypted_ni_number TEXT;
ALTER TABLE public.employee_financial_data ADD COLUMN IF NOT EXISTS encryption_version INTEGER DEFAULT 1;
ALTER TABLE public.holiday_requests ADD COLUMN IF NOT EXISTS system_user_id UUID;
ALTER TABLE public.project_tasks ADD COLUMN IF NOT EXISTS is_internal BOOLEAN DEFAULT false;
ALTER TABLE public.project_tasks ADD COLUMN IF NOT EXISTS comments JSONB DEFAULT '[]'::jsonb;
ALTER TABLE public.staff_details ADD COLUMN IF NOT EXISTS email TEXT;
ALTER TABLE public.staff_details ADD COLUMN IF NOT EXISTS name TEXT;
ALTER TABLE public.staff_details ADD COLUMN IF NOT EXISTS role TEXT;
ALTER TABLE public.staff_details ADD COLUMN IF NOT EXISTS status TEXT DEFAULT 'Active';
ALTER TABLE public.staff_details ADD COLUMN IF NOT EXISTS annual_leave_entitlement NUMERIC DEFAULT 25.0;
ALTER TABLE public.system_users ADD COLUMN IF NOT EXISTS phone_number TEXT;
ALTER TABLE public.system_users ADD COLUMN IF NOT EXISTS department TEXT;
ALTER TABLE public.system_users ADD COLUMN IF NOT EXISTS position TEXT;
ALTER TABLE public.system_users ADD COLUMN IF NOT EXISTS start_date DATE;
ALTER TABLE public.system_users ADD COLUMN IF NOT EXISTS contract_type TEXT DEFAULT 'full_time';
ALTER TABLE public.system_users ADD COLUMN IF NOT EXISTS working_hours_per_week NUMERIC DEFAULT 37.5;
ALTER TABLE public.system_users ADD COLUMN IF NOT EXISTS annual_leave_entitlement NUMERIC DEFAULT 25.0;
ALTER TABLE public.system_users ADD COLUMN IF NOT EXISTS employee_id TEXT;
ALTER TABLE public.system_users ADD COLUMN IF NOT EXISTS line_manager_id UUID;
ALTER TABLE public.system_users ADD COLUMN IF NOT EXISTS ni_number TEXT;
ALTER TABLE public.todos ADD COLUMN IF NOT EXISTS mentioned_users TEXT[] DEFAULT '{}';

-- Enable RLS
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.noticeboard ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.news_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.system_users ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.comprehensive_users ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.customers ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.billing_customers ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.customer_pricing ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.staff_details ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.employee_sensitive_data ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.employee_financial_data ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.form_templates ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.form_submissions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.proposal_tokens ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.document_shares ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.app_permissions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.status_timing_logs ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.user_status ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.user_statuses ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.todos ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.project_tasks ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.task_attachments ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.task_notifications ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.app_permission_grants ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.billing_settings ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.import_batches ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.call_logs ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.billing_periods ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.billing_invoices ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.billing_line_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.billing_data_audit ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.chat_rooms ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.chat_messages ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.chat_room_members ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.chat_message_reads ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.holiday_entitlements ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.holiday_requests ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.shift_templates ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.shift_instances ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.shift_assignments ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.shift_audit_log ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.user_skills ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.sensitive_data_access_log ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.sensitive_data_audit ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.staff_data_access_audit ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.system_users_audit_log ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.financial_data_audit_enhanced ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.financial_emergency_access ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.scheduler_settings ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.leave_quota_defaults ENABLE ROW LEVEL SECURITY;

-- Indexes (removed DATE() index that caused immutability error)
CREATE INDEX IF NOT EXISTS idx_app_permission_grants_role ON public.app_permission_grants(role);
CREATE INDEX IF NOT EXISTS idx_billing_invoices_customer_id ON public.billing_invoices(customer_id);
CREATE INDEX IF NOT EXISTS idx_billing_invoices_period ON public.billing_invoices(billing_period);
CREATE INDEX IF NOT EXISTS idx_billing_periods_customer ON public.billing_periods(customer_id);
CREATE INDEX IF NOT EXISTS idx_call_logs_batch ON public.call_logs(batch_id);
CREATE INDEX IF NOT EXISTS idx_call_logs_billing_period ON public.call_logs(billing_period);
CREATE INDEX IF NOT EXISTS idx_call_logs_customer_id ON public.call_logs(customer_id);
CREATE INDEX IF NOT EXISTS idx_call_logs_date ON public.call_logs(date);
CREATE INDEX IF NOT EXISTS idx_chat_message_reads_user_id ON public.chat_message_reads(user_id);
CREATE INDEX IF NOT EXISTS idx_chat_messages_created_at ON public.chat_messages(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_chat_messages_room_id ON public.chat_messages(room_id);
CREATE INDEX IF NOT EXISTS idx_chat_room_members_room_id ON public.chat_room_members(room_id);
CREATE INDEX IF NOT EXISTS idx_chat_room_members_user_id ON public.chat_room_members(user_id);
CREATE INDEX IF NOT EXISTS idx_customer_pricing_lookup ON public.customer_pricing(customer_id, effective_from DESC);
CREATE INDEX IF NOT EXISTS idx_holiday_entitlements_user_year ON public.holiday_entitlements(user_id, year);
CREATE INDEX IF NOT EXISTS idx_holiday_requests_dates ON public.holiday_requests(start_date, end_date);
CREATE INDEX IF NOT EXISTS idx_holiday_requests_status ON public.holiday_requests(status);
CREATE INDEX IF NOT EXISTS idx_holiday_requests_system_user_id ON public.holiday_requests(system_user_id);
CREATE INDEX IF NOT EXISTS idx_holiday_requests_user_id ON public.holiday_requests(user_id);
CREATE INDEX IF NOT EXISTS idx_proposal_tokens_token ON public.proposal_tokens(token);
CREATE INDEX IF NOT EXISTS idx_shift_assignments_instance ON public.shift_assignments(shift_instance_id);
CREATE INDEX IF NOT EXISTS idx_shift_assignments_user ON public.shift_assignments(user_id);
CREATE INDEX IF NOT EXISTS idx_shift_instances_date ON public.shift_instances(shift_date);
CREATE INDEX IF NOT EXISTS idx_shift_instances_template ON public.shift_instances(template_id);
CREATE INDEX IF NOT EXISTS idx_staff_details_user_id ON public.staff_details(user_id);
CREATE INDEX IF NOT EXISTS idx_status_timing_logs_user_timestamp ON public.status_timing_logs(user_id, timestamp);
CREATE INDEX IF NOT EXISTS idx_system_users_status_active ON public.system_users(status) WHERE status = 'Active';
CREATE INDEX IF NOT EXISTS idx_user_skills_user ON public.user_skills(user_id);
CREATE UNIQUE INDEX IF NOT EXISTS uq_system_users_user_id ON public.system_users(user_id);

-- Realtime
DO $$ BEGIN ALTER PUBLICATION supabase_realtime ADD TABLE public.chat_message_reads; EXCEPTION WHEN OTHERS THEN null; END $$;
DO $$ BEGIN ALTER PUBLICATION supabase_realtime ADD TABLE public.chat_messages; EXCEPTION WHEN OTHERS THEN null; END $$;
DO $$ BEGIN ALTER PUBLICATION supabase_realtime ADD TABLE public.chat_room_members; EXCEPTION WHEN OTHERS THEN null; END $$;
DO $$ BEGIN ALTER PUBLICATION supabase_realtime ADD TABLE public.chat_rooms; EXCEPTION WHEN OTHERS THEN null; END $$;
DO $$ BEGIN ALTER PUBLICATION supabase_realtime ADD TABLE public.holiday_entitlements; EXCEPTION WHEN OTHERS THEN null; END $$;
DO $$ BEGIN ALTER PUBLICATION supabase_realtime ADD TABLE public.holiday_requests; EXCEPTION WHEN OTHERS THEN null; END $$;
DO $$ BEGIN ALTER PUBLICATION supabase_realtime ADD TABLE public.news_items; EXCEPTION WHEN OTHERS THEN null; END $$;
DO $$ BEGIN ALTER PUBLICATION supabase_realtime ADD TABLE public.project_tasks; EXCEPTION WHEN OTHERS THEN null; END $$;
DO $$ BEGIN ALTER PUBLICATION supabase_realtime ADD TABLE public.task_notifications; EXCEPTION WHEN OTHERS THEN null; END $$;
DO $$ BEGIN ALTER PUBLICATION supabase_realtime ADD TABLE public.todos; EXCEPTION WHEN OTHERS THEN null; END $$;
DO $$ BEGIN ALTER PUBLICATION supabase_realtime ADD TABLE public.user_status; EXCEPTION WHEN OTHERS THEN null; END $$;
DO $$ BEGIN ALTER PUBLICATION supabase_realtime ADD TABLE public.user_statuses; EXCEPTION WHEN OTHERS THEN null; END $$;